name: UseImageFrontendBackoffice
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Actualizar imagen
        run: |
          cd /var/www/html/Arquitectura-de-Backoffice
          docker compose down
          docker rmi marrzuy/backoffice-frontend:latest || true
          docker pull marrzuy/backoffice-frontend:latest
      - name: Detener contenedores
        run: |
          cd /var/www/html/Arquitectura-de-Backoffice
          docker compose down
      - name: Iniciar contenedores
        run: |
          cd /var/www/html/Arquitectura-de-Backoffice
          docker compose up -d
      - name: Preparar contenedores
        run: |
          docker exec -i backoffice-backend chmod o+w ./storage/ -R  
          docker exec -i backoffice-backend php artisan key:generate
          docker exec -i backoffice-backend php artisan optimize
          