name: UseImageFrontendBackoffice
on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Actualizar imagen
        run: |
          docker rmi marrzuy/backoffice-frontend:latest || true
          docker pull marrzuy/backoffice-frontend:latest
      - name: Detener contenedores
        run: |
          cd /var/www/html/Arquitectura-de-Backoffice
          docker compose down
      - name: Iniciar contenedores
        run: |
          cd /var/www/html/Arquitectura-de-Backoffice
          docker compose up -d
